<a href="https://colab.research.google.com/github/siddharth2004agrawal/AiProject1/blob/AiModules%2Fmodule-11/Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical
import numpy as np

In [ ]:
print(f"TensorFlow Version:{tf.__version__}")

TensorFlow Version:2.20.0


In [ ]:
corpus=[
    "I love machine Learning",
    "Machine learning is fascinating",
    "I want to learn more about machine learning"
    "I like GL Bajaj"
    "siddharth is a good boy"

]

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words=len(tokenizer.word_index)+1
print(f"Word index:{tokenizer.word_index}")
print(f"Total Words in Vocabulary:{total_words}")


Word index:{'machine': 1, 'i': 2, 'learning': 3, 'is': 4, 'love': 5, 'fascinating': 6, 'want': 7, 'to': 8, 'learn': 9, 'more': 10, 'about': 11, 'learningi': 12, 'like': 13, 'gl': 14, 'bajajsiddharth': 15, 'a': 16, 'good': 17, 'boy': 18}
Total Words in Vocabulary:19


In [ ]:
 input_sequences=[]
 for line in corpus:
  token_list=tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequence=token_list[:i+1]
    input_sequences.append(n_gram_sequence)
print(f"Input Sequences:{input_sequences[:5]}")

Input Sequences:[[2, 5], [2, 5, 1], [2, 5, 1, 3], [1, 3], [1, 3, 4]]


In [ ]:
max_sequence_len=max([len(x) for x in input_sequences])
print(f"Max Sequence Length:{max_sequence_len}")
padded_sequences=np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences,maxlen=max_sequence_len,padding="pre"))
print(f"Padded Sequences:\n{padded_sequences}")

Max Sequence Length:15
Padded Sequences:
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  5  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  5  1  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  3  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  3  4  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  7  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  7  8  9]
 [ 0  0  0  0  0  0  0  0  0  0  2  7  8  9 10]
 [ 0  0  0  0  0  0  0  0  0  2  7  8  9 10 11]
 [ 0  0  0  0  0  0  0  0  2  7  8  9 10 11  1]
 [ 0  0  0  0  0  0  0  2  7  8  9 10 11  1 12]
 [ 0  0  0  0  0  0  2  7  8  9 10 11  1 12 13]
 [ 0  0  0  0  0  2  7  8  9 10 11  1 12 13 14]
 [ 0  0  0  0  2  7  8  9 10 11  1 12 13 14 15]
 [ 0  0  0  2  7  8  9 10 11  1 12 13 14 15  4]
 [ 0  0  2  7  8  9 10 11  1 12 13 14 15  4 16]
 [ 0  2  7  8  9 10 11  1 12 13 14 15  4 16 17]
 [ 2  7  8  9 10 11  1 12 13 14 15  4 16 17 18]

In [ ]:
x,labels=padded_sequences[:,:-1],padded_sequences[:,-1]
y=to_categorical(labels,num_classes=total_words)
print(f"\nshape of X (predictors):{x.shape}")
print(f"nshape of X (labels):{y.shape}")


shape of X (predictors):(20, 14)
nshape of X (labels):(20, 19)


In [ ]:
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
def predict_next_word(seed_text,n_words):
  for _ in range(n_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted_probabilities = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(predicted_probabilities)
    output_word ='"'
    for word,index in tokenizer.word_index.items():
      if index == predicted_index:
        output_word = word
        break
    seed_text += " " + output_word
  return seed_text

In [ ]:
seed_text = "I Love"
predicted_sentence=predict_next_word(seed_text,2)
print(f"Seed Text:'{seed_text}'")
print(f"Predicted Sentence:'{predicted_sentence}'")

seed_text = "Machine Learning is"
predicted_sentence=predict_next_word(seed_text,2)
print(f"Seed Text:'{seed_text}'")
print(f"Predicted Sentence:'{predicted_sentence}'")

Seed Text:'I Love'
Predicted Sentence:'I Love like like'
Seed Text:'Machine Learning is'
Predicted Sentence:'Machine Learning is " "'
